version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - "> 5.1.1"
  - dependency-name: html-webpack-plugin
    versions:
    - ">= 4.a, < 5"
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.1.0
    - 5.1.0
    - 5.2.0
    - 5.2.0
    - 5.2.0
    - 5.2.0
    - 5.3.0
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
    - 5.3.1
  - dependency-name: webpack
    versions:
    - 5.20.1
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.29.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 8.0.18
    - 8.1.0
    - 8.2.0
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: "@wasm-tool/wasm-pack-plugin"
    versions:
    - 1.3.3
  - dependency-name: typescript
    versions:
    - 4.1.4
