[package]
name = "cbor-nemo157-com"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cbor-diag = "0.1.6"
serde = "1.0.106"
futures = "0.3.4"

[dependencies.wasm-bindgen]
version = "0.2.61"
features = ["serde-serialize"]

[dev-dependencies]
anyhow = "1.0.28"
port_check = "0.1.5"
once_cell = "1.3.1"
libc = "0.2.69"
indoc = "0.3.5"
headless_chrome = "0.9.0"
pretty_env_logger = "0.4.0"
failure = "0.1.7"
serde_json = "1.0.52"
fehler = "1.0.0"
