[package]
name = "cbor-nemo157-com"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cbor-diag = "0.1.6"
serde = "1.0.105"

[dependencies.wasm-bindgen]
version = "0.2.59"
features = ["serde-serialize"]
